---
title: "Experience vs. description based decision-making project: RL model fits onto behavioral data"
output: html_notebook
---

# Set up environment and load in data

```{r}
library(tidyverse)
```

```{r}
library(rstan)
```

```{r}
helpers_path = '~/Dropbox/RangelLab/DescribedVsLearned/helpers/'
```

# Read in *clean* behavioral data

```{r}
source(paste0(helpers_path,'clean_behavioral_data.R'))
```

# Reshape data for model

```{r}
num_subjs = length(unique(clean_beh_data$subnum))

num_trials = clean_beh_data %>%
  count(subnum) %>%
  select(n)
num_trials = num_trials$n

#subjects in rows, trials in columns
choices = as.matrix(clean_beh_data %>% 
  select(subnum, choiceLeft) %>%
  group_by(subnum) %>%
  mutate(trial= 1:n()) %>%
  spread(trial, choiceLeft) %>%
  ungroup()%>%
  select(-subnum) %>%
  replace(is.na(.), -1))

outcomes_left = as.matrix(clean_beh_data %>% 
  select(subnum, leftFractalReward) %>%
  group_by(subnum) %>%
  mutate(trial= 1:n()) %>%
  spread(trial, leftFractalReward) %>%
  ungroup()%>%
  select(-subnum)%>%
  replace(is.na(.), -1))
  
outcomes_right = as.matrix(clean_beh_data %>% 
  select(subnum, rightFractalReward) %>%
  group_by(subnum) %>%
  mutate(trial= 1:n()) %>%
  spread(trial, rightFractalReward) %>%
  ungroup()%>%
  select(-subnum)%>%
  replace(is.na(.), -1))
```

# Fit model for all subjects

```{r}
m = stan_model('../helpers/stanModels/fit_qlearning.stan')
```

```{r}
m_data=list(num_subjs = num_subjs,
            num_trials = num_trials,
            choices = choices,
            outcomes_left = outcomes_left,
            outcomes_right=outcomes_right)
```

```{r}
fit = sampling(m, data=m_data)
```

# Organize output

```{r}
# Extract parameters from fit object
par_ests = data.frame(extract(fit, c("alphas", "betas")))  %>%
  gather(key, value) %>%
  separate(key, c('par', 'subj'), sep='\\.')

# Add correct subject identifiers
par_ests = data.frame(subnum = unique(clean_beh_data$subnum)) %>%
  mutate(subj = as.character(1:n())) %>%
  right_join(par_ests, by='subj') %>%
  select(-subj)
```

```{r}
par_ests %>%
  filter(par == "alphas") %>%
  ggplot(aes(value))+
  geom_histogram(alpha=.5, bins=50)+
  facet_wrap(~subnum, scales='free_y')+
  labs(title = "Posterior distribution of learning rates for each subject",
       xlab="", ylab="")
```

```{r}
par_ests %>%
  filter(par == "alphas") %>%
  group_by(subnum) %>%
  summarise(mean_alpha = mean(value),
            median_alpha = median(value))
```


```{r}
par_ests %>%
  filter(par == "betas") %>%
  ggplot(aes(value))+
  geom_histogram(alpha=.5, bins=50)+
  facet_wrap(~subnum, scales='free_y')+
  labs(title = "Posterior distribution of inverse temperatures for each subject",
       xlab="", ylab="")
```

```{r}
par_ests %>%
  filter(par == "betas") %>%
  group_by(subnum) %>%
  summarise(mean_beta = mean(value),
            median_beta = median(value))
```

Distributions of the recovered (median) parameters

```{r}
par_ests %>%
  group_by(subnum, par) %>%
  summarise(est = median(value), .groups='keep') %>%
  ggplot(aes(est))+
  geom_histogram(alpha=.5, bins=30)+
  facet_wrap(~par, scales='free_x')+
  xlab("Median estimates for all subjects")
```

Save median estimates to `clean_beh_data`

```{r}
clean_beh_data = par_ests %>%
  group_by(subnum, par) %>%
  summarise(est = median(value), .groups='keep') %>%
  spread(par, est) %>%
  left_join(clean_beh_data, by='subnum')

```

Add Q values to each trial

```{r}

get_qvals = function(subj_data){
  subj_data$leftQValue = 0
  subj_data$rightQValue = 0
  for (i in 2:nrow(subj_data)){
  subj_data$leftQValue[i] = subj_data$alphas[i] * (subj_data$leftFractalReward[i-1] - subj_data$leftQValue[i-1])
  subj_data$rightQValue[i] = subj_data$alphas[i] * (subj_data$rightFractalReward[i-1] - subj_data$rightQValue[i-1])
  }
  return(subj_data)
}

clean_beh_data = clean_beh_data %>%
  group_by(subnum) %>%
  do(get_qvals(.))

```
