---
title: "Experience vs. description based decision-making project: Adding arbitration to behavioral modeling"
output: 
  html_document:
    toc: true
    toc_float: true
    code_folding: 'hide'
---

Set up environment and load in data

```{r include=FALSE}
library(tidyverse)
library(gridExtra)
library(brms)
library(here)
cbbPalette <- c("#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
# theme_set(theme_bw())
theme_set(theme_classic())
sem <- function(x) {sd(x, na.rm=T) / sqrt(length(x))}
helpers_path = here('helpers/')
```

Simplest DDM with `valueLeft` and `valueRight` used as template.

```{r}
sim_trial = function(d, sigma, valueLeft, valueRight, barrier=1, nonDecisionTime=0, bias=0, timeStep=10, maxIter=1000){
  
  # d : drift rate
  # sigma: sd of the normal distribution 
  # timeStep: in ms
  
  RDV = bias
  time = 0
  elapsedNDT = 0
  choice = 0
  RT = NA
  
  while (time<maxIter){
    
    # If the RDV hit one of the barriers, the trial is over.
    if (RDV >= barrier | RDV <= -barrier){
      RT = (time * timeStep)/1000 #convert back to secs
      if (RDV >= barrier){
        choice = "left"
      } else if (RDV <= -barrier){
        choice = "right"
      }
      break
    } 
    
    
    if (elapsedNDT < nonDecisionTime / timeStep){
      mean = 0
      elapsedNDT = elapsedNDT + 1
    } else{
      mean = d * (valueLeft - valueRight)
    }
    
    # Sample the change in RDV from the distribution.
    RDV = RDV + rnorm(1, mean, sigma)
    
    time = time + 1
  }
  
  return(list(choice=choice, RT=RT))
}
```

```{r}
sim_trial(d=.02, sigma = .1, valueLeft=1, valueRight=1)
```

Expanded DDM that can take task specific arguments as input

```{r}
sim_trial = function(d, sigma,  barrier=1, nonDecisionTime=0, bias=0, timeStep=10, maxIter=1000, ...){
  
  # d : drift rate
  # sigma: sd of the normal distribution 
  # timeStep: in ms
  # nonDecisionTime: in ms
  # maxIter: num max samples. if a barrier isn't hit by this sampling of evidence no decision is made. If time step is 10ms and maxIter is 1000 this would be a 10sec timeout maximum
  
  RDV = bias
  time = 0
  elapsedNDT = 0
  choice = 0
  RT = NA
  kwargs = list(...)
  
  while (time<maxIter){
    
    # If the RDV hit one of the barriers, the trial is over.
    if (RDV >= barrier | RDV <= -barrier){
      RT = (time * timeStep)/1000 #convert back to secs
      if (RDV >= barrier){
        choice = "left"
      } else if (RDV <= -barrier){
        choice = "right"
      }
      break
    } 
    
    # nonDecisionTime/timeStep gives how many sampling iterations the nonDecisionTime corresponds to
    # If elapsed time is less than the number of sampling iterations required for the nonDecisionTime set evidence sampling distribution mean to 0 so any move from starting point would only be noise
    if (elapsedNDT < nonDecisionTime / timeStep){
      mean = 0
      elapsedNDT = elapsedNDT + 1
    } else{
      toUnpack = get_valDiff(EVLeft=kwargs$EVLeft, EVRight=kwargs$EVRight, QVLeft=kwargs$QVLeft, QVRight=kwargs$QVRight, probFractalDraw=kwargs$probFractalDraw)
      mean = d*toUnpack$valDiff
      out = toUnpack$out
    }
    
    # Sample the change in RDV from the distribution.
    RDV = RDV + rnorm(1, mean, sigma)
    
    # Increment sampling iteration
    time = time + 1
  }
  
  #Organize output
  addToOut = data.frame(choice=choice, reactionTime = RT)
  out = cbind(out, addToOut)
  
  return(out)
}

get_valDiff = function(EVLeft, EVRight, QVLeft, QVRight, probFractalDraw){
  
  valueLeft = probFractalDraw*QVLeft + (1-probFractalDraw)*(EVLeft)
  valueRight = probFractalDraw*QVRight + (1-probFractalDraw)*(EVRight)
  valDiff= (valueLeft - valueRight)
  
  out = data.frame(EVLeft = EVLeft, EVRight = EVRight, QVLeft = QVLeft, QVRight = QVRight, probFractalDraw = probFractalDraw)
  
  return(list(out=out, valDiff=valDiff))
}
```

Simulate one trial

```{r}
sim_trial(d=.02, sigma = .1, EVLeft=.5, EVRight = .5, QVLeft = 1.5, QVRight= .5 , probFractalDraw = 1)
```
Simulate task for one subject with their estimated QValues

```{r}
source(paste0(helpers_path,'fit_twoValSystemsWithRL_hierarchical.R'))
```

```{r}

```