---
title: "Experience vs. description based decision-making project: DDM recovery comparison"
output: 
  html_document:
    toc: true
    toc_float: true
    code_folding: 'hide'
---

# Setup

Set up environment and load in data

```{r include=FALSE}
library(tidyverse)
library(here)
cbbPalette <- c("#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
theme_set(theme_classic())
sem <- function(x) {sd(x, na.rm=T) / sqrt(length(x))}
helpers_path = here('analysis/helpers/')

set.seed(38573)
```

```{r}
source(paste0(helpers_path,'ddmSims/fit_task.R'))
source(paste0(helpers_path,'ddmSims/sim_task.R'))
source(paste0(helpers_path,'ddmSims/sim_sanity_checks.R'))
```

# Set parameters 

```{r}
d = .06
sigma = .08
rangeD = c(0.05, 0.06, 0.07)
rangeSigma = c(0.065, 0.08, 0.095)
trialsFileName=NA
trialsPerCondition=250 
numTrials = 250
numThreads = 9
verbose = FALSE
```

Create empty list that will store the trial simulators for the forthcoming models.

```{r}
sim_trial_list = list()
fit_trial_list = list()
```

# Parameter recovery

## Model 1: Simplest

```{r}
source(paste0(helpers_path, 'ddmSims/r_ddm_models/ddm_model1.R'))
```

```{r}
sim_trial_list[['model1']] = sim_trial
fit_trial_list[['model1']] = fit_trial
```

### Simulate data

```{r}
test_data = read.csv(paste0(helpers_path, 'ddmSims/test_data/test_trial_conditions.csv'))

# Replicate same conditions n times
test_data = dplyr::bind_rows(replicate(trialsPerCondition, test_data, simplify = FALSE))

# Simulate choice and RT for the replicated trial conditions
test_data = sim_task(test_data, model_name = "model1", d = d, sigma = sigma) %>%drop_na()
```

### Fit using PTA

```{r}
numModels = length(rangeD) * length(rangeSigma)
likelihoods = list()
models = c()
posteriors = list()

# Get likelihoods for all models and all artificial trials.
for (i in 1:length(rangeD)){
  curD = rangeD[i]
  for (j in 1:length(rangeSigma)){
    curSigma = rangeSigma[j]
    model = paste0(as.character(curD), ", ", as.character(curSigma))
    curFit = fit_task(test_data, model_name = "model1", pars_ = list(d=curD, sigma = curSigma))
    likelihoods[[model]] = curFit$likelihood
    models = c(models, model)
    posteriors[[model]] = 1/numModels
  }
}
```

```{r}
# Compute the posteriors.
for(t in 1:nrow(test_data)){
  denominator = 0
  for(m in 1:length(models)){
    model = models[m]
    denominator = denominator + (posteriors[[model]] * likelihoods[[model]][t]) #this indexing might be incorrect
    if(denominator == 0){
      next
    }
  }
  
  for(m in 1:length(models)){
    model = models[m]
    prior = posteriors[[model]]
    posteriors[[model]] = likelihoods[[model]][t] * prior /denominator
  }
}
```

Likelihood surface

```{r}
data.frame(m = models) %>%
  separate(m, c("d", "sigma"), sep= ",") %>%
  mutate(likelihoods = unlist(lapply(likelihoods, sum), use.names = FALSE)) %>%
  ggplot(aes(sigma, d, fill=likelihoods))+
  geom_tile()
```

Model posteriors

```{r}
data.frame(m = models) %>%
  separate(m, c("d", "sigma"), sep= ",") %>%
  mutate(posteriors = unlist(posteriors, use.names = FALSE)) %>%
  ggplot(aes(sigma, d, fill=posteriors))+
  geom_tile()


```

### Fit using MLA

```{r}

```
