---
title: 'Experience vs. description based decision-making project: Raw behavioral findings'
output:
  html_document:
    toc: yes
    toc_float: yes
    code_folding: 'hide'
  pdf_document:
    toc: yes
---

# Set up

```{r include=FALSE}
library(broom)
library(tidyverse)
theme_set(theme_bw())
library(here)
cbbPalette <- c("#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
helpers_path = here('analysis/helpers/')
source(paste0(helpers_path,'01_clean_behavioral_data.R'))
```

```{r}
source(paste0(helpers_path,'01_clean_behavioral_data.R'))
```

```{r}
clean_beh_data = clean_beh_data %>%
  mutate(EVRight = referenceProb * referenceValue,
         EVLeft = lotteryValue * lotteryProb,
         conflictTrial = ifelse( (EVLeft<EVRight) & (fractalLeftProb>fractalRightProb), "conflict", ifelse( (EVLeft>EVRight) & (fractalLeftProb<fractalRightProb), "conflict", "no conflict")), #this puts all EVLeft == EVRight trials into the no conflict bin
         leftLotteryBetter = EVLeft-EVRight>0,
         leftFractalBetter = (fractalLeftProb)-(fractalRightProb)>0,
         lotteriesSame = EVLeft == EVRight,
         fractal_diff = abs(fractalLeftProb - fractalRightProb),
         lottery_ev_diff = round(abs(EVLeft - EVRight),3),
         lottery_ev_diff = ifelse(lottery_ev_diff ==0, "no EV diff", ifelse(lottery_ev_diff == .2, "small EV diff", ifelse(lottery_ev_diff == .4, "large EV diff", NA))),
         lottery_ev_diff = factor(lottery_ev_diff, levels=c("no EV diff", "small EV diff", "large EV diff"), labels = c("no", "small", "large")),
         choseBetterLotteryBundle = ifelse(leftLotteryBetter & choiceLeft == 1, 1, ifelse(!leftLotteryBetter & choiceLeft == 0, 1, 0)),
         choseBetterFractalBundle = ifelse(leftFractalBetter & choiceLeft == 1, 1, ifelse(!leftFractalBetter & choiceLeft == 0, 1, 0)),
         leftBundleValue = (probFractalDraw*fractalLeftProb) + ((1-probFractalDraw)*EVLeft),
         rightBundleValue = (probFractalDraw * fractalRightProb) + ((1-probFractalDraw)*EVRight),
         leftBundleBetter = leftBundleValue > rightBundleValue,
         choseBetterOverallBundle = ifelse(leftBundleBetter & choiceLeft == 1, 1, ifelse(!leftBundleBetter & choiceLeft == 0, 1, 0)),
         logRt = log(reactionTime),
         probFractalDraw = as.factor(probFractalDraw))
```

```{r}
fig_out_path = paste0(here(), '/outputs/fig/')
```


```{r}
p = clean_beh_data %>%
  select(EVLeft, EVRight, fractalLeftProb, fractalRightProb, probFractalDraw, choiceLeft) %>%
  mutate(EVDiff = scale(EVLeft - EVRight), 
         fractalDiff = scale(fractalLeftProb - fractalRightProb)) %>%
  nest(data = -probFractalDraw) %>% 
  mutate(
    fit = map(data, ~ glm(choiceLeft ~ EVDiff + fractalDiff, data = .x, family=binomial(link="logit"))),
    tidied = map(fit, tidy)
  ) %>% 
  unnest(tidied) %>%
  filter(term != "(Intercept)") %>%
  select(probFractalDraw, term, estimate, std.error) %>%
  mutate(term = ifelse(term == "EVDiff", "Lottery EV difference", ifelse(term == "fractalDiff", "Fractal prob difference", NA))) %>%
  ggplot(aes(probFractalDraw, estimate, col=term, group=term))+
  geom_point(size=3)+
  geom_line(size=3)+
  geom_errorbar(aes(ymin = estimate - std.error, ymax = estimate +std.error), width=0.2,size=3)+
  geom_hline(aes(yintercept=0), linetype="dashed")+
  scale_color_manual(values = cbbPalette[1:2])+
  labs(color="", y="Logit slope estimate", x="p(Fractal)")+  
  theme(legend.position = c(.7,.88),
        legend.background = element_blank(),
        panel.grid = element_blank(),
        axis.text = element_text(size=24),
        axis.title = element_text(size=24),
        legend.text = element_text(size=20))


ggsave(file=paste0(fig_out_path, 'poster_group_logit.jpg'), p, height = 5, width=8, units="in")
p
```

```{r}
p = clean_beh_data %>%
  group_by(probFractalDraw, lottery_ev_diff) %>%
  summarise(.groups = "keep",
            mean_logRt = mean(logRt),
            sem_logRt = sd(logRt)/sqrt(n())) %>%
  ggplot(aes(probFractalDraw, mean_logRt,color=lottery_ev_diff))+
  geom_point(position=position_dodge(width=.5), size=3)+
  geom_errorbar(aes(ymin = mean_logRt - sem_logRt, ymax = mean_logRt + sem_logRt), width=0,position=position_dodge(width=.5), size=2)+
  labs(color="Lottery EV difference", y="Mean Log RT", x="p(Fractal)")+
  scale_color_manual(values = c(cbbPalette[3], cbbPalette[5:6]))+
   theme(legend.position = c(.34,.2),
        legend.background = element_blank(),
        panel.grid = element_blank(),
        axis.text = element_text(size=24),
        axis.title = element_text(size=24),
        legend.text = element_text(size=18),
        legend.title = element_text(size=20))+
  guides(color=guide_legend(nrow=1))+
  scale_y_continuous(breaks = c(-.3, 0, .3), limits=c(-.36, .36))
  

ggsave(file=paste0(fig_out_path, 'poster_rt_by_lottery_ev_diff.jpg'), p, height = 5, width=8, units="in")
p
```

```{r}
p = clean_beh_data %>%
  group_by(subnum) %>%
  mutate(fractal_prob_diff = ifelse(fractal_diff < quantile(fractal_diff, probs=c(.33))[[1]], "small",
                                    ifelse(fractal_diff > quantile(fractal_diff, probs=c(.66))[[1]], "large", "medium")),
         fractal_prob_diff = factor(fractal_prob_diff, levels=c("small", "medium", "large"))) %>%
  ungroup() %>%
  # mutate(fractal_prob_diff = factor(fractal_prob_diff, levels=c("small", "medium", "large"), labels=c("small", "medium", "large"))) %>%
  group_by(probFractalDraw, fractal_prob_diff) %>%
  summarise(.groups = "keep",
            mean_logRt = mean(logRt),
            sem_logRt = sd(logRt)/sqrt(n())) %>%
  ggplot(aes(probFractalDraw, mean_logRt,color=fractal_prob_diff))+
  geom_point(position=position_dodge(width=.5), size=3)+
  geom_errorbar(aes(ymin = mean_logRt - sem_logRt, ymax = mean_logRt + sem_logRt), width=0,position=position_dodge(width=.5), size=2)+
  labs(color="Fractal prob difference", y="Mean Log RT", x="p(Fractal)")+
  scale_color_manual(values = c(cbbPalette[3], cbbPalette[5:6]))+
   theme(legend.position = c(.34,.2),
        legend.background = element_blank(),
        panel.grid = element_blank(),
        axis.text = element_text(size=24),
        axis.title = element_text(size=24),
        legend.text = element_text(size=18),
        legend.title = element_text(size=20))+
  guides(color=guide_legend(nrow=1))+
  scale_y_continuous(breaks = c(-.3, 0, .3), limits=c(-.36, .36))
  

ggsave(file=paste0(fig_out_path, 'poster_rt_by_fractal_prob_diff.jpg'), p, height = 5, width=8, units="in")
p
```